# Gene-biotype composition per dataset

This notebook assigns every feature in `gene_total_counts.csv` to a gene biotype from the corresponding species GTF. It retains the original GTF label in `biotype` and adds a harmonized cross-species category in `biotype_group`. For each dataset and biotype it reports:

- total transcript count (the summed UMI count in these count tables);
- percentage of all counts;
- number and percentage of detected features (`total_counts > 0`);
- total number of features from that biotype represented in the count table.

In [11]:
from pathlib import Path
import gzip
import re
import subprocess

import pandas as pd
from IPython.display import display

project_path = Path("/data/groups/technologies/spatial.catalyst/Projects/2024-07-UTBenchmark-SpC")
processed_path = project_path / "data/processed"
output_path = processed_path / "plots/genes/biotypes"
output_path.mkdir(parents=True, exist_ok=True)

## Samples

In [12]:
sample_metadata = [
    {"sample": "SCA013", "sample_type": "Mouse lung",  "technology": "Visium (FFPE)",    "replicate": None, "species": "mouse", "file_path": processed_path / "Visium/SCA013/harpy/gene_total_counts.csv"},
    {"sample": "SCA014", "sample_type": "Mouse liver", "technology": "Visium (FFPE)",    "replicate": None, "species": "mouse", "file_path": processed_path / "Visium/SCA014/harpy/gene_total_counts.csv"},
    {"sample": "SCA016", "sample_type": "Mouse brain", "technology": "Visium (FFPE)",    "replicate": None, "species": "mouse", "file_path": processed_path / "Visium/SCA016/harpy/gene_total_counts.csv"},
    {"sample": "SCA015", "sample_type": "Human lung",  "technology": "Visium (FFPE)",    "replicate": None, "species": "human", "file_path": processed_path / "Visium/SCA015/harpy/gene_total_counts.csv"},

    {"sample": "SCA001", "sample_type": "Mouse lung",  "technology": "Visium HD (FFPE)", "replicate": None, "species": "mouse", "file_path": processed_path / "Visium_HD/SCA001/harpy/gene_total_counts.csv"},
    {"sample": "SCA002", "sample_type": "Mouse liver", "technology": "Visium HD (FFPE)", "replicate": None, "species": "mouse", "file_path": processed_path / "Visium_HD/SCA002/harpy/gene_total_counts.csv"},
    {"sample": "SCA003", "sample_type": "Mouse brain", "technology": "Visium HD (FFPE)", "replicate": None, "species": "mouse", "file_path": processed_path / "Visium_HD/SCA003/harpy/gene_total_counts.csv"},
    {"sample": "SCA010", "sample_type": "Human lung",  "technology": "Visium HD (FFPE)", "replicate": None, "species": "human", "file_path": processed_path / "Visium_HD/SCA010/harpy/gene_total_counts.csv"},

    {"sample": "SCA017", "sample_type": "Mouse lung",  "technology": "Visium HD (FF)",   "replicate": None, "species": "mouse", "file_path": processed_path / "Visium_HD/SCA017/harpy/gene_total_counts.csv"},
    {"sample": "SCA018", "sample_type": "Mouse liver", "technology": "Visium HD (FF)",   "replicate": None, "species": "mouse", "file_path": processed_path / "Visium_HD/SCA018/harpy/gene_total_counts.csv"},
    {"sample": "SCA019", "sample_type": "Mouse brain", "technology": "Visium HD (FF)",   "replicate": None, "species": "mouse", "file_path": processed_path / "Visium_HD/SCA019/harpy/gene_total_counts.csv"},
    {"sample": "SCA020", "sample_type": "Human lung",  "technology": "Visium HD (FF)",   "replicate": None, "species": "human", "file_path": processed_path / "Visium_HD/SCA020/harpy/gene_total_counts.csv"},

    {"sample": "SCA021", "sample_type": "Mouse liver", "technology": "Visium HD 3'",     "replicate": 1,    "species": "mouse", "file_path": processed_path / "Visium_HD/SCA021/harpy/gene_total_counts.csv"},
    {"sample": "SCA023", "sample_type": "Mouse liver", "technology": "Visium HD 3'",     "replicate": 2,    "species": "mouse", "file_path": processed_path / "Visium_HD/SCA023/harpy/gene_total_counts.csv"},
    {"sample": "SCA024", "sample_type": "Mouse brain", "technology": "Visium HD 3'",     "replicate": None, "species": "mouse", "file_path": processed_path / "Visium_HD/SCA024/harpy/gene_total_counts.csv"},
    {"sample": "FPE010", "sample_type": "Rice root",   "technology": "Visium HD 3'",     "replicate": None, "species": "rice",  "file_path": processed_path / "Visium_HD/FPE010/harpy/gene_total_counts.csv"},

    {"sample": "Exp74",  "sample_type": "Mouse brain", "technology": "BMKMANU S1000",    "replicate": None, "species": "mouse", "file_path": processed_path / "BMK_S1000/exp74/harpy/gene_total_counts.csv"},
    {"sample": "Exp101", "sample_type": "Mouse lung",  "technology": "BMKMANU S3000",    "replicate": None, "species": "mouse", "file_path": processed_path / "BMK_S3000/Exp101/harpy/gene_total_counts.csv"},
    {"sample": "Exp100", "sample_type": "Mouse liver", "technology": "BMKMANU S3000",    "replicate": None, "species": "mouse", "file_path": processed_path / "BMK_S3000/Exp100/harpy/gene_total_counts.csv"},
    {"sample": "Exp99",  "sample_type": "Mouse brain", "technology": "BMKMANU S3000",    "replicate": None, "species": "mouse", "file_path": processed_path / "BMK_S3000/Exp99/harpy/gene_total_counts.csv"},
    {"sample": "Exp102", "sample_type": "Human lung",  "technology": "BMKMANU S3000",    "replicate": None, "species": "human", "file_path": processed_path / "BMK_S3000/Exp102/harpy/gene_total_counts.csv"},
    {"sample": "psb",    "sample_type": "Rice root",   "technology": "BMKMANU S3000",    "replicate": None, "species": "rice",  "file_path": processed_path / "BMK_S3000/psb/harpy/gene_total_counts.csv"},

    {"sample": "SC12", "sample_type": "Mouse lung",  "technology": "Curio Seeker", "replicate": None, "species": "mouse", "file_path": processed_path / "Curio_seeker/SC12/harpy/gene_total_counts.csv"},
    {"sample": "SC13", "sample_type": "Mouse liver", "technology": "Curio Seeker", "replicate": None, "species": "mouse", "file_path": processed_path / "Curio_seeker/SC13/harpy/gene_total_counts.csv"},
    {"sample": "SC11", "sample_type": "Mouse brain", "technology": "Curio Seeker", "replicate": None, "species": "mouse", "file_path": processed_path / "Curio_seeker/SC11/harpy/gene_total_counts.csv"},
    {"sample": "SC14", "sample_type": "Human lung",  "technology": "Curio Seeker", "replicate": None, "species": "human", "file_path": processed_path / "Curio_seeker/SC14/harpy/gene_total_counts.csv"},

    {"sample": "Exp93-sampleSPC002",  "sample_type": "Mouse lung",  "technology": "Nova-ST", "replicate": None, "species": "mouse", "file_path": processed_path / "Nova-ST/Exp93-sampleSPC002/harpy/gene_total_counts.csv"},
    {"sample": "Exp100-sampleSPC004", "sample_type": "Mouse liver", "technology": "Nova-ST", "replicate": None, "species": "mouse", "file_path": processed_path / "Nova-ST/Exp100-sampleSPC004/harpy/gene_total_counts.csv"},
    {"sample": "Exp65-sampleSPC014",  "sample_type": "Mouse brain", "technology": "Nova-ST", "replicate": None, "species": "mouse", "file_path": processed_path / "Nova-ST/Exp65-sampleSPC014/harpy/gene_total_counts.csv"},
    {"sample": "Exp93-sampleSPC022",  "sample_type": "Human lung",  "technology": "Nova-ST", "replicate": None, "species": "human", "file_path": processed_path / "Nova-ST/Exp93-sampleSPC022/harpy/gene_total_counts.csv"},
    {"sample": "Exp100-samplePSB",    "sample_type": "Rice root",   "technology": "Nova-ST", "replicate": None, "species": "rice",  "file_path": processed_path / "Nova-ST/Exp100-samplePSB/harpy/gene_total_counts.csv"},

    {"sample": "spc002",  "sample_type": "Mouse lung",  "technology": "Stereo-Seq", "replicate": None, "species": "mouse", "file_path": processed_path / "Stereo-Seq/spc002/harpy/gene_total_counts.csv"},
    {"sample": "spc004",  "sample_type": "Mouse liver", "technology": "Stereo-Seq", "replicate": None, "species": "mouse", "file_path": processed_path / "Stereo-Seq/spc004/harpy/gene_total_counts.csv"},
    {"sample": "spc014",  "sample_type": "Mouse brain", "technology": "Stereo-Seq", "replicate": None, "species": "mouse", "file_path": processed_path / "Stereo-Seq/spc014/harpy/gene_total_counts.csv"},
    {"sample": "spc022",  "sample_type": "Human lung",  "technology": "Stereo-Seq", "replicate": None, "species": "human", "file_path": processed_path / "Stereo-Seq/spc022/harpy/gene_total_counts.csv"},
    {"sample": "psb_rice", "sample_type": "Rice root",   "technology": "Stereo-Seq", "replicate": None, "species": "rice",  "file_path": processed_path / "Stereo-Seq/psb/harpy/gene_total_counts.csv"},
]

missing_files = [str(s["file_path"]) for s in sample_metadata if not s["file_path"].exists()]
print(f"Samples: {len(sample_metadata)}; missing count files: {len(missing_files)}")
missing_files[:10]

Samples: 36; missing count files: 0

[]

## Gene annotations

The mouse, human, and rice datasets are annotated against the matching reference GTFs. Only `gene` records are used. The parser accepts either `gene_type` (mouse/human GENCODE references) or `gene_biotype` (rice Ensembl Plants reference). Original labels are retained and mapped to broader Ensembl/GENCODE-based groups for cross-species comparison. Parsed annotations are cached as small compressed CSV files, so the large GTFs only need to be scanned once.

In [13]:
gtf_paths = {
    "mouse": Path("/data/groups/technologies/spatial.catalyst/Julien/spaceranger/references/refdata-gex-mm10-2020-A/genes/genes.gtf"),
    "human": Path("/data/groups/technologies/spatial.catalyst/Julien/spaceranger/references/refdata-gex-GRCh38-2020-A/genes/genes.gtf"),
    "rice": Path("/data/groups/technologies/spatial.catalyst/Julien/spaceranger/references/IRGSP.49/genes/genes.gtf"),
}

for species, path in gtf_paths.items():
    print(f"{species:>5}: {'found' if path.exists() else 'MISSING'}  {path}")

mouse: found  /data/groups/technologies/spatial.catalyst/Julien/spaceranger/references/refdata-gex-mm10-2020-A/genes/genes.gtf
human: found  /data/groups/technologies/spatial.catalyst/Julien/spaceranger/references/refdata-gex-GRCh38-2020-A/genes/genes.gtf
 rice: found  /data/groups/technologies/spatial.catalyst/Julien/spaceranger/references/IRGSP.49/genes/genes.gtf

In [14]:
attribute_pattern = re.compile(r'(\S+) \"([^\"]*)\"')

def clean_gene_id(values):
    # Remove an optional Ensembl version suffix, e.g. ENSG...12.5 -> ENSG...12.
    return values.astype('string').str.replace(r'\.\d+$', '', regex=True)

def read_gene_annotations(gtf_path, cache_path):
    if cache_path.exists():
        return pd.read_csv(cache_path, dtype='string')

    opener = gzip.open if str(gtf_path).endswith('.gz') else open
    records = []
    with opener(gtf_path, 'rt') as handle:
        for line in handle:
            if line.startswith('#'):
                continue
            fields = line.rstrip('\n').split('\t', 8)
            if len(fields) != 9 or fields[2] != 'gene':
                continue
            attributes = dict(attribute_pattern.findall(fields[8]))
            gene_id = attributes.get('gene_id')
            if gene_id is None:
                continue
            records.append({
                'gene_id': gene_id.split('.')[0],
                'gene_name': attributes.get('gene_name'),
                'biotype': attributes.get('gene_type', attributes.get('gene_biotype', 'unannotated')),
            })

    annotations = pd.DataFrame(records).drop_duplicates('gene_id')
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    annotations.to_csv(cache_path, index=False, compression='gzip')
    return annotations

annotation_cache = output_path / 'annotation_cache'
gene_annotations = {
    species: read_gene_annotations(path, annotation_cache / f'{species}_gene_biotypes.csv.gz')
    for species, path in gtf_paths.items()
}

def harmonize_biotype(biotype):
    # Broad analysis groups based on Ensembl/GENCODE biotype classes.
    if pd.isna(biotype) or biotype == 'unannotated':
        return 'Unannotated'
    if biotype == 'tRNA_pseudogene':
        return 'Other ncRNA'
    if 'pseudogene' in biotype:
        return 'Pseudogene'
    if biotype.startswith('IG_'):
        return 'IG genes'
    if biotype.startswith('TR_'):
        return 'TR genes'
    if biotype in {'protein_coding', 'nontranslating_CDS'}:
        return 'Protein-coding'
    if biotype in {
        'lncRNA', 'lincRNA', 'antisense', 'antisense_RNA',
        'sense_intronic', 'sense_overlapping',
    }:
        return 'lncRNA'
    if biotype in {'rRNA', 'Mt_rRNA'}:
        return 'rRNA'
    if biotype in {'tRNA', 'Mt_tRNA'}:
        return 'tRNA'
    if biotype in {
        'snoRNA', 'snRNA', 'miRNA', 'pre_miRNA',
        'SRP_RNA', 'RNase_MRP_RNA',
    }:
        return 'Other ncRNA'
    return 'Other'

for annotation in gene_annotations.values():
    annotation['biotype_group'] = annotation['biotype'].map(harmonize_biotype)

# Use gene names only as a fallback and only when one name maps to one biotype.
gene_name_biotypes = {
    species: (
        annotation.dropna(subset=['gene_name', 'biotype'])
        .groupby('gene_name')['biotype']
        .agg(lambda x: x.iloc[0] if x.nunique() == 1 else pd.NA)
        .dropna()
    )
    for species, annotation in gene_annotations.items()
}

for species, annotation in gene_annotations.items():
    print(f"{species:>5}: {len(annotation):,} annotated genes; {annotation['biotype'].nunique():,} biotypes")

mouse: 32,285 annotated genes; 15 biotypes
human: 36,601 annotated genes; 15 biotypes
 rice: 38,978 annotated genes; 13 biotypes

### Biotype content of the processing references

This inventory counts the unique gene IDs assigned to each biotype in the exact processed GTF used for each species. It distinguishes a biotype that was available for quantification from one that was absent from the reference and therefore could not be detected.

In [15]:
reference_biotype_summary = pd.concat(
    [
        (
            annotation.groupby(['biotype', 'biotype_group'], dropna=False)
            .size()
            .rename('number_of_annotated_genes')
            .reset_index()
            .assign(species=species, reference_gtf=str(gtf_paths[species]))
        )
        for species, annotation in gene_annotations.items()
    ],
    ignore_index=True,
)
reference_biotype_summary['percentage_of_reference_genes'] = (
    100
    * reference_biotype_summary['number_of_annotated_genes']
    / reference_biotype_summary.groupby('species')['number_of_annotated_genes'].transform('sum')
)
reference_biotype_summary = reference_biotype_summary[[
    'species', 'reference_gtf', 'biotype', 'biotype_group',
    'number_of_annotated_genes', 'percentage_of_reference_genes',
]].sort_values(['species', 'number_of_annotated_genes'], ascending=[True, False])

reference_biotype_summary.to_csv(
    output_path / 'reference_gene_biotype_inventory.csv', index=False
)

reference_biotype_counts = (
    reference_biotype_summary
    .pivot(index='biotype', columns='species', values='number_of_annotated_genes')
    .fillna(0)
    .astype(int)
)
display(reference_biotype_counts)

reference_biotype_group_counts = (
    reference_biotype_summary
    .groupby(['biotype_group', 'species'])['number_of_annotated_genes']
    .sum()
    .unstack(fill_value=0)
)
display(reference_biotype_group_counts)

print('rRNA/tRNA annotations in the exact processing references:')
display(
    reference_biotype_summary.loc[
        reference_biotype_summary['biotype'].str.contains('rRNA|tRNA', case=False, na=False)
    ]
)

species             human  mouse   rice
biotype
IG_C_gene              14     13      0
IG_C_pseudogene         9      1      0
IG_D_gene              37     19      0
IG_J_gene              18     14      0
IG_J_pseudogene         3      0      0
IG_LV_gene              0      4      0
IG_V_gene             144    218      0
IG_V_pseudogene       188    158      0
RNase_MRP_RNA           0      0      1
SRP_RNA                 0      0      2
TR_C_gene               6      8      0
TR_D_gene               4      4      0
TR_J_gene              79     70      0
TR_J_pseudogene         4     10      0
TR_V_gene             106    144      0
TR_V_pseudogene        33     34      0
antisense_RNA           0      0      6
lncRNA              16562   9888      0
nontranslating_CDS      0      0   2185
pre_miRNA               0      0     97
protein_coding      19394  21700  35775
pseudogene              0      0      1
rRNA                    0      0    275
sense_intronic          0      0     89
snRNA                   0      0     83
snoRNA                  0      0    216
tRNA                    0      0    242
tRNA_pseudogene         0      0      6

species         human  mouse   rice
biotype_group
IG genes          213    268      0
Other ncRNA         0      0    405
Protein-coding  19394  21700  37960
Pseudogene        237    203      1
TR genes          195    226      0
lncRNA          16562   9888     95
rRNA                0      0    275
tRNA                0      0    242

rRNA/tRNA annotations in the exact processing references:

,species,reference_gtf,biotype,biotype_group,number_of_annotated_genes,percentage_of_reference_genes
37,rice,/data/groups/technologies/spatial.catalyst/Jul...,rRNA,rRNA,275,0.705526
41,rice,/data/groups/technologies/spatial.catalyst/Jul...,tRNA,tRNA,242,0.620863
42,rice,/data/groups/technologies/spatial.catalyst/Jul...,tRNA_pseudogene,Other ncRNA,6,0.015393

## Summarize each dataset

Gene IDs are matched first. For an unmatched ID, the notebook falls back to gene name only when that name has one unambiguous biotype in the GTF. Remaining features are retained as `unannotated`.

In [16]:
def summarize_biotypes(sample, annotations, gene_name_biotypes):
    # Curio Seeker tables contain gene symbols but no gene_ID column.
    # Use IDs when available and otherwise rely on the unambiguous-name map.
    columns = pd.read_csv(sample['file_path'], nrows=0).columns
    usecols = ['gene', 'total_counts'] + (['gene_ID'] if 'gene_ID' in columns else [])
    counts = pd.read_csv(
        sample['file_path'],
        usecols=usecols,
        dtype={column: 'string' for column in ['gene', 'gene_ID'] if column in usecols},
    )
    if 'gene_ID' not in counts:
        counts['gene_ID'] = pd.Series(pd.NA, index=counts.index, dtype='string')
    counts['total_counts'] = pd.to_numeric(counts['total_counts'], errors='raise').fillna(0)
    counts['gene_id_clean'] = clean_gene_id(counts['gene_ID'])

    annotated = counts.merge(
        annotations[['gene_id', 'biotype']],
        how='left',
        left_on='gene_id_clean',
        right_on='gene_id',
    )

    annotated['biotype'] = annotated['biotype'].fillna(
        annotated['gene'].map(gene_name_biotypes)
    )
    annotated['biotype'] = annotated['biotype'].fillna('unannotated')
    annotated['biotype_group'] = annotated['biotype'].map(harmonize_biotype)

    total_counts = annotated['total_counts'].sum()
    total_detected = int((annotated['total_counts'] > 0).sum())

    summary = (
        annotated.groupby(['biotype', 'biotype_group'], as_index=False, observed=True)
        .agg(
            total_transcript_count=('total_counts', 'sum'),
            number_of_features_in_count_table=('gene', 'size'),
            number_of_detected_features=('total_counts', lambda x: int((x > 0).sum())),
        )
    )
    summary['percentage_of_counts'] = 100 * summary['total_transcript_count'] / total_counts
    summary['percentage_of_detected_features'] = (
        100 * summary['number_of_detected_features'] / total_detected
    )
    summary['percentage_of_biotype_features_detected'] = (
        100 * summary['number_of_detected_features'] / summary['number_of_features_in_count_table']
    )

    metadata = {
        'sample': sample['sample'],
        'sample_type': sample['sample_type'],
        'technology': sample['technology'],
        'replicate': sample['replicate'],
        'species': sample['species'],
    }
    summary = summary.assign(**metadata)
    summary = summary[[
        'sample', 'sample_type', 'technology', 'replicate', 'species',
        'biotype', 'biotype_group',
        'total_transcript_count', 'percentage_of_counts',
        'number_of_detected_features', 'percentage_of_detected_features',
        'number_of_features_in_count_table', 'percentage_of_biotype_features_detected',
    ]].sort_values('total_transcript_count', ascending=False)

    unannotated = annotated['biotype'].eq('unannotated')
    qc = {
        **metadata,
        'number_of_features': len(annotated),
        'number_of_unannotated_features': int(unannotated.sum()),
        'percentage_of_features_annotated': 100 * (~unannotated).mean(),
        'percentage_of_counts_annotated': 100 * annotated.loc[~unannotated, 'total_counts'].sum() / total_counts,
        'total_transcript_count': total_counts,
    }
    return summary, qc, annotated[[
        'gene', 'gene_ID', 'total_counts', 'biotype', 'biotype_group',
    ]].copy()

all_summaries = []
mapping_qc = []
annotated_datasets = {}

for sample in sample_metadata:
    summary, qc, annotated = summarize_biotypes(
        sample,
        gene_annotations[sample['species']],
        gene_name_biotypes[sample['species']],
    )
    all_summaries.append(summary)
    mapping_qc.append(qc)
    annotated_datasets[(sample['technology'], sample['sample'])] = annotated

biotype_summary = pd.concat(all_summaries, ignore_index=True)
mapping_qc = pd.DataFrame(mapping_qc)

biotype_summary.to_csv(output_path / 'gene_biotype_summary_all_datasets.csv', index=False)

print(f"Saved the combined biotype table to {output_path}")

Saved the combined biotype table to /data/groups/technologies/spatial.catalyst/Projects/2024-07-UTBenchmark-SpC/data/processed/plots/genes/biotypes

In [17]:
display(mapping_qc)
display(biotype_summary.head(30))

,sample,sample_type,technology,replicate,species,number_of_features,number_of_unannotated_features,percentage_of_features_annotated,percentage_of_counts_annotated,total_transcript_count
0,SCA013,Mouse lung,Visium (FFPE),NaN,mouse,19032,0,100.000000,100.000000,44648812.0
1,SCA014,Mouse liver,Visium (FFPE),NaN,mouse,19028,0,100.000000,100.000000,549766433.0
2,SCA016,Mouse brain,Visium (FFPE),NaN,mouse,19008,0,100.000000,100.000000,75262315.0
3,SCA015,Human lung,Visium (FFPE),NaN,human,17991,0,100.000000,100.000000,17935541.0
4,SCA001,Mouse lung,Visium HD (FFPE),NaN,mouse,19032,0,100.000000,100.000000,64515249.0
5,SCA002,Mouse liver,Visium HD (FFPE),NaN,mouse,18999,0,100.000000,100.000000,413309287.0
6,SCA003,Mouse brain,Visium HD (FFPE),NaN,mouse,19011,0,100.000000,100.000000,216805241.0
7,SCA010,Human lung,Visium HD (FFPE),NaN,human,18018,0,100.000000,100.000000,39873094.0
8,SCA017,Mouse lung,Visium HD (FF),NaN,mouse,17636,0,100.000000,100.000000,99960007.0
9,SCA018,Mouse liver,Visium HD (FF),NaN,mouse,16104,0,100.000000,100.000000,561663318.0
10,SCA019,Mouse brain,Visium HD (FF),NaN,mouse,17202,0,100.000000,100.000000,230036865.0
11,SCA020,Human lung,Visium HD (FF),NaN,human,17906,0,100.000000,100.000000,230281988.0
12,SCA021,Mouse liver,Visium HD 3',1.0,mouse,17113,0,100.000000,100.000000,26819346.0
13,SCA023,Mouse liver,Visium HD 3',2.0,mouse,17547,0,100.000000,100.000000,32570757.0
14,SCA024,Mouse brain,Visium HD 3',NaN,mouse,20107,0,100.000000,100.000000,29806388.0
15,FPE010,Rice root,Visium HD 3',NaN,rice,21218,0,100.000000,100.000000,4192791.0
16,Exp74,Mouse brain,BMKMANU S1000,NaN,mouse,26705,0,100.000000,100.000000,80200825.0
17,Exp101,Mouse lung,BMKMANU S3000,NaN,mouse,27786,0,100.000000,100.000000,105076822.0
18,Exp100,Mouse liver,BMKMANU S3000,NaN,mouse,27686,0,100.000000,100.000000,448928267.0
19,Exp99,Mouse brain,BMKMANU S3000,NaN,mouse,28561,0,100.000000,100.000000,138181799.0
20,Exp102,Human lung,BMKMANU S3000,NaN,human,33449,0,100.000000,100.000000,120006706.0
21,psb,Rice root,BMKMANU S3000,NaN,rice,33222,111,99.665884,99.859516,92704504.0
22,SC12,Mouse lung,Curio Seeker,NaN,mouse,19280,2,99.989627,99.999082,1851801.0
23,SC13,Mouse liver,Curio Seeker,NaN,mouse,18970,1,99.994729,99.999026,6059088.0
24,SC11,Mouse brain,Curio Seeker,NaN,mouse,19220,1,99.994797,99.995798,3546108.0
25,SC14,Human lung,Curio Seeker,NaN,human,22303,2,99.991033,99.996549,579472.0
26,Exp93-sampleSPC002,Mouse lung,Nova-ST,NaN,mouse,20442,0,100.000000,100.000000,29953713.0
27,Exp100-sampleSPC004,Mouse liver,Nova-ST,NaN,mouse,18386,0,100.000000,100.000000,95906539.0
28,Exp65-sampleSPC014,Mouse brain,Nova-ST,NaN,mouse,20836,0,100.000000,100.000000,44789947.0
29,Exp93-sampleSPC022,Human lung,Nova-ST,NaN,human,24701,0,100.000000,100.000000,26850566.0
30,Exp100-samplePSB,Rice root,Nova-ST,NaN,rice,20758,0,100.000000,100.000000,4754456.0
31,spc002,Mouse lung,Stereo-Seq,NaN,mouse,29161,0,100.000000,100.000000,208049618.0
32,spc004,Mouse liver,Stereo-Seq,NaN,mouse,26233,0,100.000000,100.000000,222744611.0
33,spc014,Mouse brain,Stereo-Seq,NaN,mouse,28464,0,100.000000,100.000000,183979920.0
34,spc022,Human lung,Stereo-Seq,NaN,human,35609,0,100.000000,100.000000,149982260.0
35,psb_rice,Rice root,Stereo-Seq,NaN,rice,26952,0,100.000000,100.000000,17937794.0

,sample,sample_type,technology,replicate,species,biotype,biotype_group,total_transcript_count,percentage_of_counts,number_of_detected_features,percentage_of_detected_features,number_of_features_in_count_table,percentage_of_biotype_features_detected
0,SCA013,Mouse lung,Visium (FFPE),None,mouse,protein_coding,Protein-coding,44591174.0,99.870908,18964,99.642707,18964,100.0
1,SCA013,Mouse lung,Visium (FFPE),None,mouse,IG_C_gene,IG genes,41240.0,0.092365,12,0.063052,12,100.0
2,SCA013,Mouse lung,Visium (FFPE),None,mouse,lncRNA,lncRNA,6094.0,0.013649,1,0.005254,1,100.0
3,SCA013,Mouse lung,Visium (FFPE),None,mouse,TR_V_gene,TR genes,4789.0,0.010726,26,0.136612,26,100.0
4,SCA013,Mouse lung,Visium (FFPE),None,mouse,TR_C_gene,TR genes,2965.0,0.006641,7,0.036780,7,100.0
5,SCA013,Mouse lung,Visium (FFPE),None,mouse,IG_V_gene,IG genes,2550.0,0.005711,22,0.115595,22,100.0
6,SCA014,Mouse liver,Visium (FFPE),None,mouse,protein_coding,Protein-coding,549718078.0,99.991204,18959,99.637376,18959,100.0
7,SCA014,Mouse liver,Visium (FFPE),None,mouse,IG_C_gene,IG genes,31537.0,0.005736,12,0.063065,12,100.0
8,SCA014,Mouse liver,Visium (FFPE),None,mouse,lncRNA,lncRNA,9726.0,0.001769,1,0.005255,1,100.0
9,SCA014,Mouse liver,Visium (FFPE),None,mouse,TR_V_gene,TR genes,3123.0,0.000568,27,0.141896,27,100.0
10,SCA014,Mouse liver,Visium (FFPE),None,mouse,TR_C_gene,TR genes,2103.0,0.000383,7,0.036788,7,100.0
11,SCA014,Mouse liver,Visium (FFPE),None,mouse,IG_V_gene,IG genes,1866.0,0.000339,22,0.115619,22,100.0
12,SCA016,Mouse brain,Visium (FFPE),None,mouse,protein_coding,Protein-coding,75254060.0,99.989032,18941,99.647517,18941,100.0
13,SCA016,Mouse brain,Visium (FFPE),None,mouse,IG_C_gene,IG genes,5826.0,0.007741,13,0.068392,13,100.0
14,SCA016,Mouse brain,Visium (FFPE),None,mouse,TR_C_gene,TR genes,993.0,0.001319,7,0.036827,7,100.0
15,SCA016,Mouse brain,Visium (FFPE),None,mouse,TR_V_gene,TR genes,611.0,0.000812,26,0.136785,26,100.0
16,SCA016,Mouse brain,Visium (FFPE),None,mouse,lncRNA,lncRNA,501.0,0.000666,1,0.005261,1,100.0
17,SCA016,Mouse brain,Visium (FFPE),None,mouse,IG_V_gene,IG genes,324.0,0.000430,20,0.105219,20,100.0
18,SCA015,Human lung,Visium (FFPE),None,human,protein_coding,Protein-coding,17681321.0,98.582591,17960,99.827692,17960,100.0
19,SCA015,Human lung,Visium (FFPE),None,human,IG_C_gene,IG genes,244836.0,1.365088,10,0.055583,10,100.0
20,SCA015,Human lung,Visium (FFPE),None,human,lncRNA,lncRNA,6252.0,0.034858,13,0.072258,13,100.0
21,SCA015,Human lung,Visium (FFPE),None,human,TR_C_gene,TR genes,3056.0,0.017039,6,0.033350,6,100.0
22,SCA015,Human lung,Visium (FFPE),None,human,TR_J_gene,TR genes,76.0,0.000424,2,0.011117,2,100.0
23,SCA001,Mouse lung,Visium HD (FFPE),None,mouse,protein_coding,Protein-coding,64418626.0,99.850232,18963,99.637453,18963,100.0
24,SCA001,Mouse lung,Visium HD (FFPE),None,mouse,IG_C_gene,IG genes,80844.0,0.125310,13,0.068306,13,100.0
25,SCA001,Mouse lung,Visium HD (FFPE),None,mouse,lncRNA,lncRNA,7055.0,0.010935,1,0.005254,1,100.0
26,SCA001,Mouse lung,Visium HD (FFPE),None,mouse,TR_C_gene,TR genes,4467.0,0.006924,7,0.036780,7,100.0
27,SCA001,Mouse lung,Visium HD (FFPE),None,mouse,TR_V_gene,TR genes,3000.0,0.004650,26,0.136612,26,100.0
28,SCA001,Mouse lung,Visium HD (FFPE),None,mouse,IG_V_gene,IG genes,1257.0,0.001948,22,0.115595,22,100.0
29,SCA002,Mouse liver,Visium HD (FFPE),None,mouse,protein_coding,Protein-coding,413268781.0,99.990200,18932,99.647350,18932,100.0

## Biotype composition of overlapping genes
Within each tissue type, a gene is **shared across all datasets** when it has `total_counts > 0` in every included dataset. Overlap is calculated separately for each tissue type, so only biologically matched samples are compared.

Two complementary results are saved:

1. **Feature composition:** the number and percentage of shared genes assigned to each biotype. This is one result per tissue type because all datasets share the same gene set by definition.
2. **Count composition:** for every dataset, the UMI counts contributed by each biotype among the shared genes. This can differ between datasets even though the identities of the shared genes are fixed.

For comparison, each per-dataset table also contains genes detected in that dataset that are *not* shared across all datasets. This is a convenient comparison group, but it should not be interpreted as genes unique to that dataset.

In [18]:
def resolve_biotype(values):
    unique = pd.unique(values.dropna())
    if len(unique) == 1:
        return unique[0]
    if len(unique) == 0:
        return 'unannotated'
    return 'ambiguous'

def collapse_to_gene_symbols(frame):
    # genes.R defines overlap by gene symbol. Collapse any repeated symbols first.
    return (
        frame.dropna(subset=['gene'])
        .groupby('gene', as_index=False, observed=True)
        .agg(
            total_counts=('total_counts', 'sum'),
            biotype=('biotype', resolve_biotype),
            biotype_group=('biotype_group', resolve_biotype),
        )
    )

overlap_feature_summaries = []
overlap_dataset_summaries = []

for sample_type in sorted({sample['sample_type'] for sample in sample_metadata}):
    tissue_samples = [sample for sample in sample_metadata if sample['sample_type'] == sample_type]
    detected_tables = {}

    for sample in tissue_samples:
        key = (sample['technology'], sample['sample'])
        table = collapse_to_gene_symbols(annotated_datasets[key])
        detected_tables[key] = table.loc[table['total_counts'] > 0].copy()

    common_genes = set.intersection(
        *(set(table['gene']) for table in detected_tables.values())
    )

    # Resolve one consistent biotype per gene across all datasets of this tissue.
    tissue_biotypes = (
        pd.concat(
            [table[['gene', 'biotype']] for table in detected_tables.values()],
            ignore_index=True,
        )
        .groupby('gene', observed=True)['biotype']
        .agg(resolve_biotype)
    )
    tissue_biotype_groups = (
        pd.concat(
            [table[['gene', 'biotype_group']] for table in detected_tables.values()],
            ignore_index=True,
        )
        .groupby('gene', observed=True)['biotype_group']
        .agg(resolve_biotype)
    )

    shared = pd.DataFrame({'gene': sorted(common_genes)})
    shared['biotype'] = shared['gene'].map(tissue_biotypes).fillna('unannotated')
    shared['biotype_group'] = (
        shared['gene'].map(tissue_biotype_groups).fillna('Unannotated')
    )
    shared.insert(0, 'sample_type', sample_type)
    feature_summary = (
        shared.groupby(['biotype', 'biotype_group'], as_index=False, observed=True)
        .agg(number_of_shared_features=('gene', 'size'))
    )
    feature_summary['percentage_of_shared_features'] = (
        100 * feature_summary['number_of_shared_features'] / len(shared)
    )
    feature_summary.insert(0, 'number_of_datasets', len(tissue_samples))
    feature_summary.insert(0, 'sample_type', sample_type)
    overlap_feature_summaries.append(feature_summary)

    for sample in tissue_samples:
        key = (sample['technology'], sample['sample'])
        frame = detected_tables[key].copy()
        frame['biotype'] = frame['gene'].map(tissue_biotypes).fillna('unannotated')
        frame['biotype_group'] = (
            frame['gene'].map(tissue_biotype_groups).fillna('Unannotated')
        )
        frame['gene_set'] = 'not_shared_across_all_datasets'
        frame.loc[frame['gene'].isin(common_genes), 'gene_set'] = 'shared_across_all_datasets'

        summary = (
            frame.groupby(
                ['gene_set', 'biotype', 'biotype_group'],
                as_index=False,
                observed=True,
            )
            .agg(
                total_umi_count=('total_counts', 'sum'),
                number_of_detected_features=('gene', 'size'),
            )
        )
        summary['percentage_of_counts_within_gene_set'] = (
            100 * summary['total_umi_count']
            / summary.groupby('gene_set')['total_umi_count'].transform('sum')
        )
        summary['percentage_of_features_within_gene_set'] = (
            100 * summary['number_of_detected_features']
            / summary.groupby('gene_set')['number_of_detected_features'].transform('sum')
        )
        summary['percentage_of_all_dataset_counts'] = (
            100 * summary['total_umi_count'] / frame['total_counts'].sum()
        )
        summary['percentage_of_all_detected_features'] = (
            100 * summary['number_of_detected_features'] / len(frame)
        )
        summary.insert(0, 'species', sample['species'])
        summary.insert(0, 'replicate', sample['replicate'])
        summary.insert(0, 'technology', sample['technology'])
        summary.insert(0, 'sample', sample['sample'])
        summary.insert(0, 'sample_type', sample_type)
        overlap_dataset_summaries.append(summary)

overlap_feature_summary = pd.concat(overlap_feature_summaries, ignore_index=True)
overlap_dataset_summary = pd.concat(overlap_dataset_summaries, ignore_index=True)
overlap_feature_summary.to_csv(
    output_path / 'shared_gene_biotype_composition_by_tissue.csv', index=False
)
overlap_dataset_summary.to_csv(
    output_path / 'overlap_biotype_composition_all_datasets.csv', index=False
)

print(f"Saved the two combined overlap tables to {output_path}")
print(
    overlap_feature_summary.groupby('sample_type')['number_of_shared_features']
    .sum()
    .rename('number_of_genes_shared_across_all_datasets')
)

Saved the two combined overlap tables to /data/groups/technologies/spatial.catalyst/Projects/2024-07-UTBenchmark-SpC/data/processed/plots/genes/biotypes
sample_type
Human lung     14325
Mouse brain    14263
Mouse liver    12731
Mouse lung     14315
Rice root      18462
Name: number_of_genes_shared_across_all_datasets, dtype: int64

In [19]:
display(overlap_feature_summary)
display(overlap_dataset_summary.head(30))

,sample_type,number_of_datasets,biotype,biotype_group,number_of_shared_features,percentage_of_shared_features
0,Human lung,7,IG_C_gene,IG genes,10,0.069808
1,Human lung,7,TR_C_gene,TR genes,6,0.041885
2,Human lung,7,ambiguous,ambiguous,1,0.006981
3,Human lung,7,lncRNA,lncRNA,8,0.055846
4,Human lung,7,protein_coding,Protein-coding,14300,99.825480
5,Mouse brain,9,IG_C_gene,IG genes,6,0.042067
6,Mouse brain,9,TR_C_gene,TR genes,3,0.021033
7,Mouse brain,9,lncRNA,lncRNA,1,0.007011
8,Mouse brain,9,protein_coding,Protein-coding,14253,99.929889
9,Mouse liver,9,IG_C_gene,IG genes,7,0.054984
10,Mouse liver,9,TR_C_gene,TR genes,3,0.023565
11,Mouse liver,9,lncRNA,lncRNA,1,0.007855
12,Mouse liver,9,protein_coding,Protein-coding,12720,99.913597
13,Mouse lung,7,IG_C_gene,IG genes,10,0.069857
14,Mouse lung,7,TR_C_gene,TR genes,7,0.048900
15,Mouse lung,7,lncRNA,lncRNA,1,0.006986
16,Mouse lung,7,protein_coding,Protein-coding,14297,99.874258
17,Rice root,4,RNase_MRP_RNA,Other ncRNA,1,0.005417
18,Rice root,4,SRP_RNA,Other ncRNA,2,0.010833
19,Rice root,4,nontranslating_CDS,Protein-coding,390,2.112447
20,Rice root,4,protein_coding,Protein-coding,18019,97.600477
21,Rice root,4,rRNA,rRNA,16,0.086665
22,Rice root,4,snRNA,Other ncRNA,8,0.043332
23,Rice root,4,snoRNA,Other ncRNA,24,0.129997
24,Rice root,4,tRNA,tRNA,2,0.010833

,sample_type,sample,technology,replicate,species,gene_set,biotype,biotype_group,total_umi_count,number_of_detected_features,percentage_of_counts_within_gene_set,percentage_of_features_within_gene_set,percentage_of_all_dataset_counts,percentage_of_all_detected_features
0,Human lung,SCA015,Visium (FFPE),None,human,not_shared_across_all_datasets,TR_J_gene,TR genes,76.0,2,0.007813,0.054555,0.000424,0.011117
1,Human lung,SCA015,Visium (FFPE),None,human,not_shared_across_all_datasets,lncRNA,lncRNA,999.0,5,0.102697,0.136388,0.005570,0.027792
2,Human lung,SCA015,Visium (FFPE),None,human,not_shared_across_all_datasets,protein_coding,Protein-coding,971687.0,3659,99.889490,99.809056,5.417662,20.337947
3,Human lung,SCA015,Visium (FFPE),None,human,shared_across_all_datasets,IG_C_gene,IG genes,244836.0,10,1.443372,0.069808,1.365088,0.055583
4,Human lung,SCA015,Visium (FFPE),None,human,shared_across_all_datasets,TR_C_gene,TR genes,3056.0,6,0.018016,0.041885,0.017039,0.033350
5,Human lung,SCA015,Visium (FFPE),None,human,shared_across_all_datasets,ambiguous,ambiguous,690.0,1,0.004068,0.006981,0.003847,0.005558
6,Human lung,SCA015,Visium (FFPE),None,human,shared_across_all_datasets,lncRNA,lncRNA,5253.0,8,0.030968,0.055846,0.029288,0.044467
7,Human lung,SCA015,Visium (FFPE),None,human,shared_across_all_datasets,protein_coding,Protein-coding,16708944.0,14300,98.503577,99.825480,93.161082,79.484187
8,Human lung,SCA010,Visium HD (FFPE),None,human,not_shared_across_all_datasets,TR_J_gene,TR genes,268.0,2,0.020180,0.054157,0.000672,0.011100
9,Human lung,SCA010,Visium HD (FFPE),None,human,not_shared_across_all_datasets,lncRNA,lncRNA,788.0,5,0.059336,0.135391,0.001976,0.027750
10,Human lung,SCA010,Visium HD (FFPE),None,human,not_shared_across_all_datasets,protein_coding,Protein-coding,1326971.0,3686,99.920484,99.810452,3.327986,20.457320
11,Human lung,SCA010,Visium HD (FFPE),None,human,shared_across_all_datasets,IG_C_gene,IG genes,1128118.0,10,2.926751,0.069808,2.829271,0.055500
12,Human lung,SCA010,Visium HD (FFPE),None,human,shared_across_all_datasets,TR_C_gene,TR genes,9291.0,6,0.024104,0.041885,0.023301,0.033300
13,Human lung,SCA010,Visium HD (FFPE),None,human,shared_across_all_datasets,ambiguous,ambiguous,1024.0,1,0.002657,0.006981,0.002568,0.005550
14,Human lung,SCA010,Visium HD (FFPE),None,human,shared_across_all_datasets,lncRNA,lncRNA,8811.0,8,0.022859,0.055846,0.022098,0.044400
15,Human lung,SCA010,Visium HD (FFPE),None,human,shared_across_all_datasets,protein_coding,Protein-coding,37397823.0,14300,97.023630,99.825480,93.792127,79.365079
16,Human lung,SCA020,Visium HD (FF),None,human,not_shared_across_all_datasets,TR_J_gene,TR genes,98.0,2,0.003553,0.055850,0.000043,0.011169
17,Human lung,SCA020,Visium HD (FF),None,human,not_shared_across_all_datasets,lncRNA,lncRNA,353.0,5,0.012797,0.139626,0.000153,0.027924
18,Human lung,SCA020,Visium HD (FF),None,human,not_shared_across_all_datasets,protein_coding,Protein-coding,2757911.0,3574,99.983650,99.804524,1.197623,19.959790
19,Human lung,SCA020,Visium HD (FF),None,human,shared_across_all_datasets,IG_C_gene,IG genes,36702865.0,10,16.131452,0.069808,15.938227,0.055847
20,Human lung,SCA020,Visium HD (FF),None,human,shared_across_all_datasets,TR_C_gene,TR genes,53642.0,6,0.023576,0.041885,0.023294,0.033508
21,Human lung,SCA020,Visium HD (FF),None,human,shared_across_all_datasets,ambiguous,ambiguous,10953.0,1,0.004814,0.006981,0.004756,0.005585
22,Human lung,SCA020,Visium HD (FF),None,human,shared_across_all_datasets,lncRNA,lncRNA,26314.0,8,0.011565,0.055846,0.011427,0.044678
23,Human lung,SCA020,Visium HD (FF),None,human,shared_across_all_datasets,protein_coding,Protein-coding,190729852.0,14300,83.828592,99.825480,82.824477,79.861499
24,Human lung,Exp102,BMKMANU S3000,None,human,not_shared_across_all_datasets,IG_C_gene,IG genes,2757490.0,4,8.439609,0.020916,2.297780,0.011959
25,Human lung,Exp102,BMKMANU S3000,None,human,not_shared_across_all_datasets,IG_C_pseudogene,Pseudogene,1077517.0,9,3.297862,0.047061,0.897881,0.026907
26,Human lung,Exp102,BMKMANU S3000,None,human,not_shared_across_all_datasets,IG_D_gene,IG genes,2.0,2,0.000006,0.010458,0.000002,0.005979
27,Human lung,Exp102,BMKMANU S3000,None,human,not_shared_across_all_datasets,IG_J_gene,IG genes,787.0,14,0.002409,0.073206,0.000656,0.041855
28,Human lung,Exp102,BMKMANU S3000,None,human,not_shared_across_all_datasets,IG_J_pseudogene,Pseudogene,2.0,2,0.000006,0.010458,0.000002,0.005979
29,Human lung,Exp102,BMKMANU S3000,None,human,not_shared_across_all_datasets,IG_V_gene,IG genes,16539.0,142,0.050619,0.742522,0.013782,0.424527