In [1]:
import pandas as pd
df = pd.read_csv(r'd:\Data\2024-07-UTBenchmark-SpC\data\processed\BMK\exp74\exp74_26Aug2024\umi_gene.tsv.gz', sep='\t', header=None)
df

                               0             1                   2  3
0         bc1_10-bc2_318-bc3_243  AAAGCCTTGCTG  ENSMUSG00000031310  8
1         bc1_10-bc2_318-bc3_243  AACTTTGGTAAG  ENSMUSG00000028309  2
2         bc1_109-bc2_54-bc3_136  GCGCATCTTTGG  ENSMUSG00000064345  3
3         bc1_109-bc2_54-bc3_136  GGATGCAAAGTA  ENSMUSG00000032355  1
4         bc1_109-bc2_54-bc3_136  TATGCACCAGCA  ENSMUSG00000022425  2
...                          ...           ...                 ... ..
80200820  bc1_19-bc2_183-bc3_368  GGTAGGCAAGCA  ENSMUSG00000015749  9
80200821  bc1_19-bc2_183-bc3_368  AGAGTTTGAACT  ENSMUSG00000030428  2
80200822  bc1_19-bc2_183-bc3_368  GGACCCTAATTG  ENSMUSG00000031851  6
80200823  bc1_19-bc2_183-bc3_368  ACGGAAATCTTA  ENSMUSG00000064354  1
80200824  bc1_19-bc2_183-bc3_368  GACCGACGTTTG  ENSMUSG00000031633  8

[80200825 rows x 4 columns]

In [2]:
df[3].sum()

306554789

In [3]:
df = pd.read_csv(r'd:\Data\2024-07-UTBenchmark-SpC\data\processed\BMK\exp74\exp74_26Aug2024\bc_umi_read.tsv.gz', sep='\t', header=None)
df

                               0             1  2
0         bc1_10-bc2_318-bc3_243  AAAGCCTTGCTG  8
1         bc1_10-bc2_318-bc3_243  AACTTTGGTAAG  2
2         bc1_109-bc2_54-bc3_136  GCGCATCTTTGG  3
3         bc1_109-bc2_54-bc3_136  GGATGCAAAGTA  1
4         bc1_109-bc2_54-bc3_136  TATGCACCAGCA  2
...                          ...           ... ..
80200820  bc1_19-bc2_183-bc3_368  GGTAGGCAAGCA  9
80200821  bc1_19-bc2_183-bc3_368  AGAGTTTGAACT  2
80200822  bc1_19-bc2_183-bc3_368  GGACCCTAATTG  6
80200823  bc1_19-bc2_183-bc3_368  ACGGAAATCTTA  1
80200824  bc1_19-bc2_183-bc3_368  GACCGACGTTTG  8

[80200825 rows x 3 columns]